
// Code generated by charts/generate_charts.go go generate; DO NOT EDIT.
package codefresh_charts

import (
	"helm.sh/helm/v3/pkg/chart/loader"
)

func ChartsMap() map[string][]*loader.BufferedFile {
  chartsMap := make(map[string][]*loader.BufferedFile)
	var fileName, fileData string

	
	/********
	/*
    Chart directory codefresh-operator
	*/
	
	//--------------------------------
	fileName = "Chart.yaml"
	fileData = `apiVersion: "v1"
name: cf-onprem-operator
version: 1.0.0`
	bufferedFile = &loader.BufferedFile{Name: fileName, Data: []byte(fileData)}
	chartsMap["codefresh-operator"] = append(chartsMap["codefresh-operator"], bufferedFile)

	
	//--------------------------------
	fileName = "templates/crd.yaml"
	fileData = `apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: codefreshes.charts.helm.k8s.io
spec:
  group: charts.helm.k8s.io
  names:
    kind: Codefresh
    listKind: CodefreshList
    plural: codefreshes
    singular: codefresh
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
`
	bufferedFile = &loader.BufferedFile{Name: fileName, Data: []byte(fileData)}
	chartsMap["codefresh-operator"] = append(chartsMap["codefresh-operator"], bufferedFile)

	
	//--------------------------------
	fileName = "templates/operator.yaml"
	fileData = `apiVersion: apps/v1
kind: Deployment
metadata:
  name: cf-onprem-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cf-onprem-operator
  template:
    metadata:
      labels:
        name: cf-onprem-operator
    spec:
      serviceAccountName: cf-onprem-operator
      containers:
        - name: cf-onprem-operator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "cf-onprem-operator"
`
	bufferedFile = &loader.BufferedFile{Name: fileName, Data: []byte(fileData)}
	chartsMap["codefresh-operator"] = append(chartsMap["codefresh-operator"], bufferedFile)

	
	//--------------------------------
	fileName = "templates/role.yaml"
	fileData = `apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: cf-onprem-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - services/finalizers
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - '*'
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - cf-onprem-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - apps
  resources:
  - replicasets
  - deployments
  verbs:
  - get
- apiGroups:
  - charts.helm.k8s.io
  resources:
  - '*'
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
`
	bufferedFile = &loader.BufferedFile{Name: fileName, Data: []byte(fileData)}
	chartsMap["codefresh-operator"] = append(chartsMap["codefresh-operator"], bufferedFile)

	
	//--------------------------------
	fileName = "templates/role_binding.yaml"
	fileData = `kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cf-onprem-operator
subjects:
- kind: ServiceAccount
  name: cf-onprem-operator
roleRef:
  kind: Role
  name: cf-onprem-operator
  apiGroup: rbac.authorization.k8s.io
`
	bufferedFile = &loader.BufferedFile{Name: fileName, Data: []byte(fileData)}
	chartsMap["codefresh-operator"] = append(chartsMap["codefresh-operator"], bufferedFile)

	
	//--------------------------------
	fileName = "templates/service_account.yaml"
	fileData = `apiVersion: v1
kind: ServiceAccount
metadata:
  name: cf-onprem-operator
`
	bufferedFile = &loader.BufferedFile{Name: fileName, Data: []byte(fileData)}
	chartsMap["codefresh-operator"] = append(chartsMap["codefresh-operator"], bufferedFile)

	
	//--------------------------------
	fileName = "values.yaml"
	fileData = `dummy: "1"`
	bufferedFile = &loader.BufferedFile{Name: fileName, Data: []byte(fileData)}
	chartsMap["codefresh-operator"] = append(chartsMap["codefresh-operator"], bufferedFile)

	
	
	return chartsMap
}
